### ISSUE TITLE
Cable Fibre + Gaine PVC

### ISSUE THREAD

**Issue by alexis-opolka** [alexis-opolka/Vert#2]
Chercher le coût cable fibre et de la gaine PVC, ce qui veut dire calculer la longueur de notre fibre.

**Comment by Mathys-Domergue** [comment]
Prix des câbles pour 1843.25 m de fibre = 3.504,24 € TTC source : https://www.fs.com/fr/products/30976.html?attribute=6158&id=1027176
Prix de la gaine de protection = 447,36 € TTC source : https://www.essentracomponents.com/fr-fr/p/gaines-de-protection-fibre-optique/ofbltp-31-505pp?indexed=true

**Comment by ThibaultGarcia** [comment]
nouvelle distance : 1873,75m

**Comment by ThibaultGarcia** [comment]
câbles : 3.539,50 €
(gaîne inchangée)
