### ISSUE TITLE
Poteaux + etc

### ISSUE THREAD

**Issue by alexis-opolka** [alexis-opolka/Vert#5]

**Comment by ThibaultGarcia** [comment]
Poteau + installation intégrale (fondations, dressage du poteau...) = 25 000€ à 50 000€

Source : technicien Orange.

**Comment by ThibaultGarcia** [comment]
Espace entre chaque poteau : 30m à 100m

**Comment by ThibaultGarcia** [comment]
Minimum : 10 * 25 000 = 250 000 €

Maximum : 10 * 50 000 = 500 000 €
